run:
  tests: false

issues:
  fix: false

  max-issues-per-linter: 0
  max-same-issues: 0

linters:
  enable-all: true
  disable:
    # Deprecated.
    - varcheck
    - maligned
    - scopelint
    - structcheck
    - nosnakecase
    - interfacer
    - ifshort
    - golint
    - deadcode
    - exhaustivestruct

    # Handle formatting separately.
    - gci
    - gofmt
    - gofumpt
    - goimports

    # Not useful here
    - depguard
    - nlreturn

linters-settings:
  exhaustruct:
    exclude:
      - "^github.com/urfave/cli/v2.App$"
      - "^github.com/urfave/cli/v2.BoolFlag$"
      - "^github.com/urfave/cli/v2.Command$"
      - "^github.com/urfave/cli/v2.StringFlag$"
