before:
  hooks:
    - go mod tidy

# ----------------------------------- Build ---------------------------------- #

builds:
  - id: gdenv
    main: ./cmd/gdenv
    mod_timestamp: "{{ .CommitTimestamp }}"
    env:
      - CGO_ENABLED=0
      - GODEBUG=zipinsecurepath=0,tarinsecurepath=0
    targets:
      - darwin_amd64
      - darwin_arm64
      - linux_amd64
      - windows_amd64

  - id: gdenv-shim
    binary: gdenv-shim
    main: ./cmd/gdenv-shim
    env:
      - CGO_ENABLED=0
    mod_timestamp: "{{ .CommitTimestamp }}"
    targets:
      - darwin_amd64
      - darwin_arm64
      - linux_amd64
      - windows_amd64

# --------------------------------- Release --------------------------------- #

archives:
  # The 'gdenv-shim' binary should not be separately archived; it's included
  # in the 'gdenv' archive.
  - id: gdenv-shim
    format: binary

  - id: gdenv
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    files:
      # Include the 'gdenv-shim' binary for the appropriate build target
      - gdenv-shim_{{ .Os }}_{{ .Arch }}/*
    name_template: >-
      {{ .ProjectName }}-v{{ .Version }}-

      {{- if eq .Os "darwin" }}macos
      {{- else }}{{ .Os }}{{ end }}-

      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}

changelog:
  skip: true

checksum:
  name_template: checksums.txt
  ids:
    - gdenv
