before:
  hooks:
    - go mod tidy

# ----------------------------------- Build ---------------------------------- #

builds:
  - env:
      - CGO_ENABLED=0
    mod_timestamp: "{{ .CommitTimestamp }}"
    targets:
      - darwin_amd64
      - darwin_arm64
      - linux_amd64
      - windows_amd64

# --------------------------------- Release --------------------------------- #

archives:
  - format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    files:
      - none*
    name_template: >-
      {{ .ProjectName }}-{{ .Version }}-

      {{- if eq .Os "darwin" }}macos
      {{- else }}{{ .Os }}{{ end }}-

      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}

changelog:
  skip: true

checksum:
  name_template: "checksums.txt"
