name: "🤖 Set up: 'gdenv' executable"
description: "Install the specified version of 'gdenv'."

inputs:
  version:
    description: "The version of 'gdenv' to install."
    required: false
    default: "latest"
  install-dir:
    description: "The 'gdenv' installation directory."
    required: false
    default: "$HOME/.gdenv"
  modify-path:
    description: "Whether to add the 'gdenv' command to 'PATH'."
    required: false
    default: true
  project-dir:
    description: "A path to a Godot project containing a version file."
    required: false
    default: "."
  skip-install:
    description: "Whether to skip installing the Godot binary."
    required: false
    default: false

runs:
  using: "composite"
  steps:
    - name: Export the 'GDENV_HOME' environment variable
      shell: bash
      run: echo "GDENV_HOME=${{ inputs.install-dir }}" >> $GITHUB_ENV

    - name: Cache the 'gdenv' home directory
      id: cache-gdenv
      uses: actions/cache@v4
      with:
        path: ${{ env.GDENV_HOME }}
        key: gdenv-${{ runner.os }}-${{ inputs.version }}-${{ inputs.install-dir }}-${{ hashFiles(format('{0}/**/.godot-version', inputs.project-dir)) }}
        restore-keys: |
          gdenv-${{ runner.os }}-${{ inputs.version }}-${{ inputs.install-dir }}-

    # See https://github.com/coffeebeats/gdenv/blob/main/docs/installation.md#linuxmacos.
    - name: Install 'gdenv' (latest)
      if: steps.cache-gdenv.outputs.cache-hit != 'true' && inputs.version == 'latest'
      shell: bash
      run: |
        curl https://raw.githubusercontent.com/coffeebeats/gdenv/main/scripts/install.sh | sh -s -- --no-modify-path

    # See https://github.com/coffeebeats/gdenv/blob/main/docs/installation.md#manual-download.
    - name: Install 'gdenv'
      if: steps.cache-gdenv.outputs.cache-hit != 'true' && inputs.version != 'latest'
      shell: bash
      run: |
        ARCH=x86_64
        OS="$(echo "$(uname -s)" | tr '[:upper:]' '[:lower:]')"
        VERSION="$(echo "${{ inputs.version }}" | sed 's/^v//')"

        curl -LO "https://github.com/coffeebeats/gdenv/releases/download/v${VERSION#v}/gdenv-$VERSION-$OS-$ARCH.tar.gz"

        mkdir -p $GDENV_HOME/bin && \
        tar -C $GDENV_HOME/bin -xf gdenv-$VERSION-$OS-$ARCH.tar.gz

    - name: Update the 'PATH' environment variable
      if: inputs.modify-path == 'true'
      shell: bash
      run: echo "$GDENV_HOME/bin" >> $GITHUB_PATH

    - name: Validate that the 'gdenv' executable was installed
      shell: bash
      run: |
        if ! command -v gdenv >/dev/null; then
          echo "Failed to install 'gdenv'!"
          exit 1
        fi

    - name: Install Godot editor
      if: inputs.skip-install == 'false'
      continue-on-error: true
      shell: bash
      run: gdenv --path ${{ inputs.project-dir }} install
